# Generated by Django 4.0.3 on 2022-04-16 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new image', max_length=200)),
                ('location', models.CharField(choices=[('TORONTO', 'Toronto'), ('VANCOUVER', 'Vancouver'), ('CALGARY', 'Calgary'), ('MONTREAL', 'Montreal'), ('HALIFAX', 'Halifax'), ('WHITEHORSE', 'WhiteHorse'), ('WINNIPEG', 'Winnipeg'), ('QUEBEC CITY', 'Quebec City'), ('OTTAWA', 'Ottawa')], default='Toronto', max_length=200)),
                ('category', models.CharField(default='travel', max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(default='image', max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.imageinfo')),
            ],
        ),
    ]
